using HarmonyLib;
using SandBox.GameComponents;
using SandBox.GauntletUI.AutoGenerated1;
using System;
using System.Linq;
using System.Reflection;
using TaleWorlds.Core;
using TaleWorlds.Engine;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade;
using TaleWorlds.MountAndBlade.ComponentInterfaces;


namespace NoThrustCollisions {

        public class SubModule : MBSubModuleBase {

        /* ----------------- MBSUBMODULEBASE OVERRIDES ----------------- */

        protected override void OnGameStart(Game game, IGameStarter gameStarterObject) {
            base.OnGameStart(game, gameStarterObject);

            NoThrustDamageModel thrustModel = new NoThrustDamageModel();
            gameStarterObject.AddModel(thrustModel);
        }

        public override void OnMissionBehaviorInitialize(Mission mission) {

            if (mission == null) {
                return;
            }

            base.OnMissionBehaviorInitialize(mission);
        }


        protected override void OnSubModuleLoad() {
            
            base.OnSubModuleLoad();
            //Harmony harmony = new Harmony("mod.no_thrust_collision");
            //harmony.PatchAll();

        }


    }
}

    



